# Generated by Django 4.2.2 on 2023-06-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivosmodel',
            old_name='imagem',
            new_name='imagem_play',
        ),
        migrations.RenameField(
            model_name='arquivosmodel',
            old_name='musica',
            new_name='music_play',
        ),
    ]
