# Generated by Django 4.2.2 on 2023-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_imagem_arquivosmodel_imagem_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmodel',
            name='artist',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivosmodel',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
