# Generated by Django 4.2.2 on 2023-06-24 14:04

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_arquivosmodel_artist_arquivosmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosmodel',
            name='imagem_play',
            field=models.ImageField(upload_to=music.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='arquivosmodel',
            name='music_play',
            field=models.FileField(upload_to=music.models.upload_music_to),
        ),
    ]
