# Generated by Django 4.2.2 on 2023-06-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loguin',
            new_name='Login',
        ),
    ]
