# Generated by Django 4.2.2 on 2023-06-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_loguin_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
