# Generated by Django 4.2.2 on 2023-06-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_email_alter_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.AddField(
            model_name='login',
            name='cadastro',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
