# Generated by Django 4.2.2 on 2023-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_login_email_remove_login_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='last_login',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
