# Generated by Django 4.2.2 on 2023-06-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_login_last_login_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='cadastro',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='login.cadastro'),
            preserve_default=False,
        ),
    ]
