# Generated by Django 4.2.2 on 2023-06-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
