# Generated by Django 4.2.2 on 2023-06-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_delete_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telephone',
            field=models.CharField(max_length=200),
        ),
    ]
