# Generated by Django 4.2.2 on 2023-06-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_cadastro_password_alter_cadastro_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
