# Generated by Django 4.2.2 on 2023-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_cadastro_email_alter_cadastro_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('musica', models.FileField(upload_to='musicas/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='CadastroModel',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
