# Generated by Django 4.2.2 on 2023-06-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_arquivosmodel_rename_cadastro_cadastromodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArquivosModel',
        ),
    ]
