# Generated by Django 4.2.3 on 2023-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_delete_arquivosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
