# Generated by Django 4.2.3 on 2023-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_cadastromodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastromodel',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='city',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='date_of_birth',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='neighborhood',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='telephone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
