# Generated by Django 4.2.3 on 2023-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_cadastromodel_cep_cadastromodel_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastromodel',
            old_name='date_of_birth',
            new_name='birthdate',
        ),
    ]
