# Generated by Django 4.2.3 on 2023-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_rename_date_of_birth_cadastromodel_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastromodel',
            old_name='neighborhood',
            new_name='bairro',
        ),
        migrations.AddField(
            model_name='cadastromodel',
            name='uf',
            field=models.CharField(default='', max_length=30),
        ),
    ]
