# Generated by Django 4.2.3 on 2023-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=80)),
                ('birthdate', models.DateField()),
                ('cep', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=80)),
                ('uf', models.CharField(default='', max_length=30)),
                ('bairro', models.CharField(default='', max_length=80)),
                ('country', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('terms', models.BooleanField(default=True)),
            ],
        ),
    ]
