# Generated by Django 4.2.2 on 2023-07-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='imagem_play',
            field=models.ImageField(default=2, upload_to='videos/imagem'),
            preserve_default=False,
        ),
    ]
